name: Testing

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: bash test.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test_report
      - name: Status Report
        run: |
            if [ `cat test_report/result.txt` = 1 ]
            then
                exit 1
            fi
        shell: bash
